title: 'GPT-4 Vision Add-On'
description: |
  Analyze tables and forms in your documents using GPT-4 Vision.
  Disclosure: This Add-On uses AI. It only runs when you tell it to. It can run on any public document 
  or any private document that you have access to. It cannot access documents you don't have access to. 
  You may read more about OpenAI's [training](https://help.openai.com/en/articles/7842364-how-chatgpt-and-our-foundation-models-are-developed) 
  and [privacy policy]( https://openai.com/policies/row-privacy-policy/) to learn more. 

instructions: ''
type: object
documents:
  - selected
properties:
  start_page:
    title: Start page
    type: integer
    description: 'Page number where the table(s) begin'
    default: 1
  end_page:
    title: End page
    type: integer
    description: 'Page number where table(s) end'
    default: 1
  prompt:
    title: Prompt
    type: string
    description: 'GPT-4 prompt to provide for analysis. This field is optional, there is a default prompt.'
  output_format:
    title: 'Output format'
    type: string
    default: csv
    enum:
      - csv
      - json
categories:
  - extraction
  - ai
  - premium
cost:
  price: 7
  amount: 1
  unit: page
version: 2
